### ISSUE TITLE
Update translation into Spanish

### ISSUE THREAD

**Issue by franco999** [vishnunaini/lineage-surnia-releases#1]
I was testing this ROM in my Moto XT1527 and I liked it, but it lacked several translations and I would like to know where to be able to help in that.

**Comment by xpaixx** [comment]
Same in Polish

**Comment by vishnunaini** [comment]
Please help out with the translations here 

https://crowdin.com/project/lineageos

**Comment by vishnunaini** [comment]
Also see here https://crowdin.com/project/lineageos-aosp for languages not supported in aosp.

**Comment by vishnunaini** [comment]
Since I import upstream translations as and when they are available any changes have to come from upstream.

Contributions can be made to the crowdin projects linked above.

Thanks for reporting. Please contribute to LineageOS directly.

**Comment by vishnunaini** [comment]
Go to the crowdin page for the specific language and edit the strings.xml file for whom the translations are not 100%

**Comment by vishnunaini** [comment]
If you want to make edits for this device only the components to edit for the device specific changes are msm8916-common and surnia

**Comment by franco999** [comment]
@vishnunaini  Several days ago I translated 100% of the strings in Crowdin and I still do not see that they have updated the translation in Github (LineageOS and here).

Do you know how long it takes to update the translated strings?

**Comment by vishnunaini** [comment]
When CM had official builds the jenkins instance used to automatically pull translations across all repositories every night and push automated patches to gerrit everyday. Maintainers manually reviewed them and merged them.

After the migration to LineageOS the jenkins instance is not running full time yet because of some code changes required. The devs are currently working on a platform to distribute jenkins builds over multiple remote servers contributed by volunteers.They are also working on major code changes to lineageos updater. Once official lineageos builds start within this week or so the jenkins translation pull bot will be back in operation and will be submitting patches everyday.

I am not going to manually pull updates from crowdin as there are hundreds of individual repositories that make android and I don't have the time or scripts to pull them and review them. I will wait for the bot to be back up and running. Give it a week or two.

**Comment by franco999** [comment]
Great. Now it is clearer why the non-importation.

As I am somewhat new to this ROMs (the first ROM I installed was CM in Dec 2016), I was not aware of why the problem.

Hopefully see what happens. Thanks for the clarification.

**Comment by vishnunaini** [comment]
Updated translations are now imported into the new release

https://github.com/vishnunaini/lineage-surnia-releases/releases/tag/20170126
