### ISSUE TITLE
ROOT ACCESS 

### ISSUE THREAD

**Issue by psyfii** [vishnunaini/lineage-surnia-releases#7]
**Root access** seems to disabled, no way to activate or deactivate. After installation of ROM,Gapps and wiping cache/dalvik it asks to **install SU**, on confirmation(swipe to install)  it just goes to the android startup logo remains there, don't think this's boot loop. Any suggestions?

I don't see the option of update under **About phone**

**Comment by vishnunaini** [comment]
Do not use the Supersu bundled with twrp. It is old and incompatible with Android 7.1.1.
 Get the latest supersu from chainfire or magisk and flash the zip using twrp.

The updater was removed because this ROM is signed using test keys and it is insecure to allow OTA's on something that is signed with test keys. Updates have to be done by manually downloading the zip and flashing it.

If there is something else, reopen the issue.

**Comment by 003cyriac** [comment]
Try searching for "modified supersu for one plus one" that works well for me. Lineage os root will still be disabled,but can use root permission on supersu
